dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

script:
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support terraform init
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support terraform fmt -check=true
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support terraform validate -check-variables=false
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support tf_readme_validator.py
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support cred-alert scan -f .
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support tflint --error-with-issues --ignore-module="terraform-aws-modules/vpc/aws"
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t leandelivery/docker-terraform-ci:tf-12-support terrascan --location . --test all